[project]
name = "lancedb"
version = "0.5.8"
dependencies = [
    "deprecation",
    "pylance==0.9.18",
    "ratelimiter~=1.0",
    "retry>=0.9.2",
    "tqdm>=4.27.0",
    "pydantic>=1.10",
    "attrs>=21.3.0",
    "semver>=3.0",
    "cachetools",
    "pyyaml>=6.0",
    "click>=8.1.7",
    "requests>=2.31.0",
    "overrides>=0.7",
]
description = "lancedb"
authors = [{ name = "LanceDB Devs", email = "dev@lancedb.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "data-format",
    "data-science",
    "machine-learning",
    "arrow",
    "data-analytics",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]

[project.urls]
repository = "https://github.com/lancedb/lancedb"

[project.optional-dependencies]
tests = [
    "aiohttp",
    "pandas>=1.4",
    "pytest",
    "pytest-mock",
    "pytest-asyncio",
    "duckdb",
    "pytz",
    "polars>=0.19",
]
dev = ["ruff", "pre-commit"]
docs = [
    "mkdocs",
    "mkdocs-jupyter",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-ultralytics-plugin==0.0.44",
]
clip = ["torch", "pillow", "open-clip"]
embeddings = [
    "openai>=1.6.1",
    "sentence-transformers",
    "torch",
    "pillow",
    "open-clip-torch",
    "cohere",
    "huggingface_hub",
    "InstructorEmbedding",
    "google.generativeai",
    "boto3>=1.28.57",
    "awscli>=1.29.57",
    "botocore>=1.31.57",
]

[tool.maturin]
python-source = "python"
module-name = "lancedb._lancedb"

[project.scripts]
lancedb = "lancedb.cli.cli:cli"

[build-system]
requires = ["maturin>=1.4"]
build-backend = "maturin"


[tool.ruff]
select = ["F", "E", "W", "I", "G", "TCH", "PERF"]

[tool.pytest.ini_options]
addopts = "--strict-markers --ignore-glob=lancedb/embeddings/*.py"

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "asyncio",
]
